### ISSUE TITLE
[Question] Cythonize the package for faster speed?

### ISSUE THREAD

**Issue by greenspray9** [Ibotta/pure-predict#9]
This is already quite a fast package. Can we crazier and move all the pure python code to Cython code? I am new to Cython and I am not sure if that would increase the speed. What do you think?

**Comment by denver1117** [comment]
This could help, but the intent/vision of pure predict is to make deployment packages as lightweight as possible. So requiring Cython in a deployment container or serverless package would violate this. Said differently, the intent is to navigate the tradeoff between deployment package size (explicit cost and cold start latency for serverless applications) and prediction latency. 

For small prediction size, we actually get better latency than with numpy (numpy gives us big gains with linear algebra operations for large 2-D arrays, but for shape (1,N), we are better off with pure python in some cases). I'm not sure where Cython optimized pure python (rather than Cython optimized numpy) would fall here. But shipping a really clean/lightweight/fast deployment package for serverless (eg. AWS Lambdas on off-the-shelf python environments) is truly the goal.
